name: build tauri app
permissions:
  # needs write as soon as it creates releases
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUST_BACKTRACE: 1

concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true

jobs:
  build-app:
    runs-on: ${{ matrix.os }}
    strategy:
      # let all os builds run, even if one fails
      fail-fast: false
      matrix:
        # https://docs.github.com/en/actions/how-tos/write-workflows/choose-where-workflows-run/choose-the-runner-for-a-job#standard-github-hosted-runners-for-public-repositories
        # choose oldes linux for glibc compatiblity
        # choose macos-15-intel for intel mac builds
        # choose windows-latest for windows
        os: [ubuntu-22.04, macos-15-intel, windows-latest]

    steps:
      - uses: actions/checkout@v6

      - name: Install and cache APT packages
        if: startsWith(matrix.os, 'ubuntu')
        uses: gerlero/apt-install@v1.3.11
        with:
          # APT packages to install
          packages: libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Install NSIS on Windows
        if: startsWith(matrix.os, 'windows')
        run: choco install nsis -y

      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup Rust environment
        uses: dtolnay/rust-toolchain@1.100.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v6.2.0
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: v24.13.0
          # Target architecture for Node to use. Examples: x86, x64. Will use system architecture by default.
          # architecture: # optional

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.1.2
        with:
          # The version of Bun to install. (e.g. "latest", "canary", "1.0.0", "1.0.x", <sha>)
          bun-version: 1.1.19

      - run: cd src-tauri && cargo build --release
        name: compile backend
      - run: cd src-tauri && cargo test --release
        name: run backend tests

      - run: bun install
        name: install frontend dependencies
      - run: bun run check
        name: generate base config in ./.svelte-kit/tsconfig.json
      - run: bun tauri build
        name: create bundles

      - name: Upload macOS bundle artifacts
        uses: actions/upload-artifact@v6
        if: startsWith(matrix.os, 'macOS')
        with:
          name: tauri-bundles-${{ matrix.os }}
          path: |
            src-tauri/target/release/bundle/macos/*.app
            src-tauri/target/release/bundle/dmg/*.dmg

      - name: Upload Windows bundle artifacts
        uses: actions/upload-artifact@v6
        if: startsWith(matrix.os, 'windows')
        with:
          name: tauri-bundles-${{ matrix.os }}
          path: |
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/nsis/*.exe

      - name: Upload Linux bundle artifacts
        uses: actions/upload-artifact@v6
        if: startsWith(matrix.os, 'ubuntu')
        with:
          name: tauri-bundles-${{ matrix.os }}
          path: |
            src-tauri/target/release/bundle/deb/*.deb
            src-tauri/target/release/bundle/rpm/*.rpm
            src-tauri/target/release/bundle/appimage/*.AppImage
